name: STGames-Huur
version: '${project.version}'
main: me.max.stgameshuur.Main
depend:
  - WorldGuard
  - MinetopiaSDB
  - Vault
  - Citizens
api-version: '1.19'
commands:
  huur:
    description: /huur command
    permission: stgames.huur
  categorie:
    description: /categorie command
    permission: stgames.categorie
  huurplot:
    description: /huurplot command
    permission: stgames.huurplot